### ISSUE TITLE
how to bypass 192.168.1.0/24

### ISSUE THREAD

**Issue by zcrself** [jpkrause/AndroidProxySetter#11]
I have set '-e bypass 192.168', but this command is no valid.

**Comment by manadream** [comment]
Hm, this is another one where I don't think it's possible with the current implementation. Basically, if you can't do it in the `Advanced options` section of the Wifi Access Point settings, probably can't do it with this app. If I have some time I'll look into it.

**Comment by zcrself** [comment]
great, If this app can bypass test.com, I would think that it could also
bypass one ip address, such as 192.168.1.1

**Comment by manadream** [comment]
It can definitely bypass `192.168.1.1`, but you stated that you entered `192.168` as the bypass. If you run the command like `adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e host 10.0.3.2 -e port 8080 -e bypass 192.168.1.1` it will set the bypass to that IP address

**Comment by zcrself** [comment]
I try it again

**Comment by zcrself** [comment]
I have tried your command, it is no valid. it will be not proxy all http
accessing.

my tk.elevenk.proxysetter version is versionName=0.1.3

my script is as follows:

adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e host
192.168.1.9 -e port 8118 -e bypass 202.127.18.227

**Comment by manadream** [comment]
It's not clear what the issue is at this point. If you execute that command it should change the device's proxy settings to what you have there. Can you give me some logcat logs or tell me what error you are seeing?

**Comment by zcrself** [comment]
D/ProxySetterApp( 5823): Warning: No SSID given, setting on the fist one available
V/ProxySetterApp( 5823): Executing Change Request
V/ProxySetterApp( 5823): *Begin Intent Details*
V/ProxySetterApp( 5823): action: null
V/ProxySetterApp( 5823): component: ComponentInfo{tk.elevenk.proxysetter/tk.elevenk.proxysetter.MainActivity}
V/ProxySetterApp( 5823): key [bypass]: plex.tv
V/ProxySetterApp( 5823): key [host]: 192.168.1.9
V/ProxySetterApp( 5823): key [port]: 8118
V/ProxySetterApp( 5823): *End Intent Details*
I/WifiManager( 5823): Wifi getConfiguredNetworks called by tk.elevenk.proxysetter
I/Vlog    (18839): PfxPrecog:WarmvCold:fgtracking=false;DV;1,key=cold;DV;1,Counter=1.000000;CT;1,unit=null;DV;1,metadata=version%231%7Cmode%23active%7Cpkg%23tk.elevenk.proxysetter%7C;DV;1:HI
I/Vlog    (18839): PfxPrecog:AppTransition:fgtracking=false;DV;1,key=AppTransition;DV;1,Counter=0.000000;CT;1,unit=null;DV;1,metadata=version%231%7Cprevious_package%23com.plexapp.android%7Cnew_package%23tk.elevenk.proxysetter%7C;DV;1:HI
V/WindowManager( 1823): Adding window Window{32a632e1 u0 tk.elevenk.proxysetter/tk.elevenk.proxysetter.MainActivity} at 8 of 9 (after Window{1aa8b967 u0 com.plexapp.android/com.plexapp.plex.activities.tv.PreplayMovieActivity})
D/ProxySetterApp( 5823): {'dd-wrt' - 'SECURITY_PSK'=* ID: 2 SSID: "dd-wrt" BSSID: any FQDN: null REALM: null PRIO: 144
D/ProxySetterApp( 5823):  numAssociation 50
D/ProxySetterApp( 5823):  validatedInternetAccess
D/ProxySetterApp( 5823):  KeyMgmt: WPA_PSK Protocols: WPA RSN
D/ProxySetterApp( 5823):  AuthAlgorithms:
D/ProxySetterApp( 5823):  PairwiseCiphers: CCMP
D/ProxySetterApp( 5823):  GroupCiphers: WEP40 WEP104 TKIP CCMP
D/ProxySetterApp( 5823):  PSK: *
D/ProxySetterApp( 5823): Enterprise config:
D/ProxySetterApp( 5823): password NULL
D/ProxySetterApp( 5823): subject_match NULL
D/ProxySetterApp( 5823): engine 0
D/ProxySetterApp( 5823): client_cert NULL
D/ProxySetterApp( 5823): ca_cert NULL
D/ProxySetterApp( 5823): anonymous_identity NULL
D/ProxySetterApp( 5823): identity NULL
D/ProxySetterApp( 5823): key_id NULL
D/ProxySetterApp( 5823): engine_id NULL
D/ProxySetterApp( 5823): phase2 NULL
D/ProxySetterApp( 5823): eap NULL
D/ProxySetterApp( 5823): IP config:
D/ProxySetterApp( 5823): IP assignment: DHCP
D/ProxySetterApp( 5823): Proxy settings: STATIC
D/ProxySetterApp( 5823): HTTP proxy: [192.168.1.9] 8118 xl=202.127,192.168
D/ProxySetterApp( 5823):  uid=1000 autoJoinBSSID=anyroamingFailureBlackListTimeMilli: 1000
D/ProxySetterApp( 5823): triggeredLow: 0 triggeredBad: 0 triggeredNotHigh: 0
D/ProxySetterApp( 5823): ticksLow: 0 ticksBad: 0 ticksNotHigh: 0
D/ProxySetterApp( 5823): triggeredJoin: 0
D/ProxySetterApp( 5823): autoJoinBailedDueToLowRssi: false
D/ProxySetterApp( 5823): autoJoinUseAggressiveJoinAttemptThreshold: 0
D/ProxySetterApp( 5823): , 'dd-wrt' - 'SECURITY_NONE'=ID: 1 SSID: "dd-wrt" BSSID: null FQDN: null REALM: null PRIO: 0
D/ProxySetterApp( 5823):  KeyMgmt: NONE Protocols: WPA RSN
D/ProxySetterApp( 5823):  AuthAlgorithms:
D/ProxySetterApp( 5823):  PairwiseCiphers: TKIP CCMP
D/ProxySetterApp( 5823):  GroupCiphers: WEP40 WEP104 TKIP CCMP
D/ProxySetterApp( 5823):  PSK: 
D/ProxySetterApp( 5823): Enterprise config:
D/ProxySetterApp( 5823): password NULL
D/ProxySetterApp( 5823): subject_match NULL
D/ProxySetterApp( 5823): engine 0
D/ProxySetterApp( 5823): client_cert NULL
D/ProxySetterApp( 5823): ca_cert NULL
D/ProxySetterApp( 5823): anonymous_identity NULL
D/ProxySetterApp( 5823): identity NULL
D/ProxySetterApp( 5823): key_id NULL
D/ProxySetterApp( 5823): engine_id NULL
D/ProxySetterApp( 5823): phase2 NULL
D/ProxySetterApp( 5823): eap NULL
D/ProxySetterApp( 5823): IP config:
D/ProxySetterApp( 5823): IP assignment: DHCP
D/ProxySetterApp( 5823): Proxy settings: STATIC
D/ProxySetterApp( 5823): HTTP proxy: [192.168.1.9] 8118 xl=plex.tv
D/ProxySetterApp( 5823):  uid=10039roamingFailureBlackListTimeMilli: 1000
D/ProxySetterApp( 5823): triggeredLow: 0 triggeredBad: 0 triggeredNotHigh: 0
D/ProxySetterApp( 5823): ticksLow: 0 ticksBad: 0 ticksNotHigh: 0
D/ProxySetterApp( 5823): triggeredJoin: 4
D/ProxySetterApp( 5823): autoJoinBailedDueToLowRssi: false
D/ProxySetterApp( 5823): autoJoinUseAggressiveJoinAttemptThreshold: 0
D/ProxySetterApp( 5823): , '360免费WiFi-1F' - 'SECURITY_PSK'=ID: 0 SSID: "360免费WiFi-1F" BSSID: null FQDN: null REALM: null PRIO: 6
D/ProxySetterApp( 5823):  numAssociation 5
D/ProxySetterApp( 5823):  validatedInternetAccess
D/ProxySetterApp( 5823):  KeyMgmt: WPA_PSK Protocols: WPA RSN
D/ProxySetterApp( 5823):  AuthAlgorithms:
D/ProxySetterApp( 5823):  PairwiseCiphers: CCMP
D/ProxySetterApp( 5823):  GroupCiphers: WEP40 WEP104 TKIP CCMP
D/ProxySetterApp( 5823):  PSK: *
D/ProxySetterApp( 5823): Enterprise config:
D/ProxySetterApp( 5823): password NULL
D/ProxySetterApp( 5823): subject_match NULL
D/ProxySetterApp( 5823): engine 0
D/ProxySetterApp( 5823): client_cert NULL
D/ProxySetterApp( 5823): ca_cert NULL
D/ProxySetterApp( 5823): anonymous_identity NULL
D/ProxySetterApp( 5823): identity NULL
D/ProxySetterApp( 5823): key_id NULL
D/ProxySetterApp( 5823): engine_id NULL
D/ProxySetterApp( 5823): phase2 NULL
D/ProxySetterApp( 5823): eap NULL
D/ProxySetterApp( 5823): IP config:
D/ProxySetterApp( 5823): IP assignment: DHCP
D/ProxySetterApp( 5823): Proxy settings: NONE
D/ProxySetterApp( 5823):  uid=1000roamingFailureBlackListTimeMilli: 1000
D/ProxySetterApp( 5823): triggeredLow: 0 triggeredBad: 0 triggeredNotHigh: 0
D/ProxySetterApp( 5823): ticksLow: 0 ticksBad: 0 ticksNotHigh: 0
D/ProxySetterApp( 5823): triggeredJoin: 0
D/ProxySetterApp( 5823): autoJoinBailedDueToLowRssi: false
D/ProxySetterApp( 5823): autoJoinUseAggressiveJoinAttemptThreshold: 0
D/ProxySetterApp( 5823): }
D/ProxySetterApp( 5823): Network ID dd-wrt with security SECURITY_PSK does not match requirements ssid = null and isSecured = false
I/WifiManager( 5823): Wifi getConfiguredNetworks called by tk.elevenk.proxysetter
I/WifiManager( 5823): Wifi getConfiguredNetworks called by tk.elevenk.proxysetter
D/ProxySetterApp( 5823): Received broadcast about wifi. Connected = true
V/ProxySetterApp( 5823): *Begin Intent Details*
V/ProxySetterApp( 5823): action: android.net.conn.CONNECTIVITY_CHANGE
V/ProxySetterApp( 5823): component: null
V/ProxySetterApp( 5823): key [networkInfo]: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "dd-wrt", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
V/ProxySetterApp( 5823): key [networkType]: 1
V/ProxySetterApp( 5823): key [inetCondition]: 0
V/ProxySetterApp( 5823): key [extraInfo]: "dd-wrt"
V/ProxySetterApp( 5823): *End Intent Details*
E/WiFiServiceImpl ( 1823): SAVE nid=0 uid=10039/1000
D/WifiService( 1823): Connect with configID: 1 SSID: "dd-wrt" BSSID: null FQDN: null REALM: null PRIO: 0
D/WifiService( 1823):  KeyMgmt: NONE Protocols: WPA RSN
D/WifiService( 1823):  AuthAlgorithms:
D/WifiService( 1823):  PairwiseCiphers: TKIP CCMP
D/WifiService( 1823):  GroupCiphers: WEP40 WEP104 TKIP CCMP
D/WifiService( 1823):  PSK: 
D/WifiService( 1823): Enterprise config:
D/WifiService( 1823): password NULL
D/WifiService( 1823): subject_match NULL
D/WifiService( 1823): engine 0
D/WifiService( 1823): client_cert NULL
D/WifiService( 1823): ca_cert NULL
D/WifiService( 1823): anonymous_identity NULL
D/WifiService( 1823): identity NULL
D/WifiService( 1823): key_id NULL
D/WifiService( 1823): engine_id NULL
D/WifiService( 1823): phase2 NULL
D/WifiService( 1823): eap NULL
D/WifiService( 1823): IP config:
D/WifiService( 1823): IP assignment: DHCP
D/WifiService( 1823): Proxy settings: STATIC
D/WifiService( 1823): HTTP proxy: [192.168.1.9] 8118 xl=plex.tv
D/WifiService( 1823):  uid=10039roamingFailureBlackListTimeMilli: 1000
D/WifiService( 1823): triggeredLow: 0 triggeredBad: 0 triggeredNotHigh: 0
D/WifiService( 1823): ticksLow: 0 ticksBad: 0 ticksNotHigh: 0
D/WifiService( 1823): triggeredJoin: 4
D/WifiService( 1823): autoJoinBailedDueToLowRssi: false
D/WifiService( 1823): autoJoinUseAggressiveJoinAttemptThreshold: 0
E/WifiStateMachine( 1823): SAVE_NETWORK id=1 config="dd-wrt" nid=1 supstate=CompletedState my state ConnectedState
E/WifiConfigStore( 1823): will read network variables netId=1
D/ProxySetterApp( 5823): Executing proxy change request...
I/LoggerMetricsFactoryImpl( 1823): PhoneWindowManager:ActivityChanged:tk.elevenk.proxysetter=1.0;CT;1:NR
I/Vlog    ( 1823): ScreenTime:PackageScreenTime:fgtracking=false;DV;1,key=com.plexapp.android;DV;1,Timer=0.03985194444444445;TI;1,unit=hours;DV;1:HI
I/LoggerMetricsFactoryImpl( 1823): PhoneWindowManager:ScreenTime:endTimeMs=1.481965758407E12;TI;1,startTimeMs=1.48196561494E12;TI;1,com.plexapp.android=143467.0;TI;1:NR
I/LoggerMetricsFactoryImpl( 1823): ScreenTime:updateLRUListLocked:page-type=KindleFramework;CK;1,hitType=deviceAction;CK;1,team-name=KindleFramework;CK;1,site_variant=KindleApplication;CK;1,page-action=fgEnd;CK;1,sub-page-type=com.plexapp.android;CK;1,RequestId=DFB90842A986ABFC6821;DV;1:NA
I/LoggerMetricsFactoryImpl( 1823): ScreenTime:updateLRUListLocked:page-type=KindleFramework;CK;1,hitType=deviceAction;CK;1,team-name=KindleFramework;CK;1,site_variant=KindleApplication;CK;1,page-action=fgStart;CK;1,sub-page-type=tk.elevenk.proxysetter;CK;1,RequestId=C1582C4F1B8A6995EA9F;DV;1:NA
E/WifiAutoJoinController ( 1823): updateConfigurationHistory found 1 networks
E/WifiAutoJoinController ( 1823):     compareWifiConfigurations NULL band status!
E/WifiAutoJoinController ( 1823): updateConfigurationHistory add a choice "dd-wrt"NONE over "dd-wrt"WPA_PSK choice 30
E/WifiAutoJoinController ( 1823): updateConfigurationHistory try to connect to an old network!! : "dd-wrt"NONE
E/WifiConfigStore( 1823):  rewrite network history for "dd-wrt"NONE
I/HAL     ( 5823): loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8960.so hmi=0x0 handle=0xaec4a544
I/HAL     ( 5823): loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8960.so hmi=0x0 handle=0xaec4a544
I/Vlog    ( 1823): Fluidity:warm_launch_time:fgtracking=false;DV;1,key=tk.elevenk.proxysetter/.MainActivity;DV;1,Timer=123508.0;TI;1,unit=ms;DV;1:HI
I/ActivityManager( 1823): Displayed tk.elevenk.proxysetter/.MainActivity: +164ms (total +2m3s508ms)
I/WifiManager( 5823): Wifi getConfiguredNetworks called by tk.elevenk.proxysetter
D/ProxySetterApp( 5823): Proxy on dd-wrt with security SECURITY_NONE set to 192.168.1.9:8118 bypass: plex.tv
D/ProxySetterApp( 5823): Checking wifi connectivity...
I/AndroidRuntime( 7721): To Report FATAL to activityManagerService
I/ActivityManager( 1823): handleApplicationCrash
D/ActivityManager( 1823): Ignoring request to show crash dialog - MASTER_DISABLE_ANR_CRASH_DIALOGS_KEY set
I/ActivityManager( 1823): addErrorToDropBox inserted hashcode=753e1027f56af382c00c732edd5afae075d84f43 for eventType crash.
I/AndroidRuntime( 7721): Finished reporting FATAL to activityManagerService
I/Vlog    ( 1823): 1p_2p:bg_crash:fgtracking=false;DV;1,key=com.android.providers.downloads;DV;1,Counter=1.0;CT;1,unit=count;DV;1,metadata=753e1027f56af382c00c732edd5afae075d84f43;DV;1:HI
I/CrashDescriptorUtil( 1823): addErrorToCommonLog Hash already present in file
I/ActivityManager( 1823): Process com.android.providers.downloads (pid 7721) has died
I/Vlog    ( 1823): activity_manager_service:sample_lifetime:fgtracking=false;DV;1,key=com.android.providers.downloads;DV;1,Counter=236566.0;CT;1,unit=ms;DV;1,metadata=com.android.providers.downloads;DV;1:HI
I/Vlog    ( 1823): activity_manager_service:sample_died_oom_adj:fgtracking=false;DV;1,key=oom_adj_5;DV;1,Counter=1.0;CT;1,unit=;DV;1,metadata=com.android.providers.downloads/com.android.providers.downloads;DV;1:HI
W/ActivityManager( 1823): Scheduling restart of crashed service com.android.providers.downloads/.DownloadService in 10000ms
V/P2PEngine(  590): force reannounce magnet:?xt=urn:btih:32b28a2d8e3718aff0a35cd612de5513fcfd95a0&dht=btrouter1.aiseejapp.atianqi.com:10098&dht=btrouter2.aiseejapp.atianqi.com:10098
I/HAL     ( 5823): loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8960.so hmi=0x0 handle=0xaec4a544
I/Vlog    ( 1823): activity_manager_service:sample_pss:fgtracking=false;DV;1,key=com.bubblesoft.android.bubbleupnp;DV;1,Counter=11609.0;CT;1,unit=kB;DV;1,metadata=com.bubblesoft.android.bubbleupnp/CE;DV;1:HI
I/Vlog    ( 1823): activity_manager_service:sample_uss:fgtracking=false;DV;1,key=com.bubblesoft.android.bubbleupnp;DV;1,Counter=10448.0;CT;1,unit=kB;DV;1,metadata=com.bubblesoft.android.bubbleupnp/CE;DV;1:HI
D/ProxySetterApp( 5823): Wifi connected and proxy set!
D/BatteryStatsExtension.VitalEmitterBatteryAndTime( 1823): VitalEmitterBatteryAndTime.start(-): not runnable
I/AndroidRuntime(18839): To Report FATAL to activityManagerService
I/ActivityManager( 1823): handleApplicationCrash
I/LoggerMetricsFactoryImpl( 1823): PhoneWindowManager:ActivityChanged:com.plexapp.android=1.0;CT;1:NR
I/Vlog    ( 1823): ScreenTime:PackageScreenTime:fgtracking=false;DV;1,key=tk.elevenk.proxysetter;DV;1,Timer=6.030555555555556E-4;TI;1,unit=hours;DV;1:HI
I/LoggerMetricsFactoryImpl( 1823): PhoneWindowManager:ScreenTime:tk.elevenk.proxysetter=2171.0;TI;1,endTimeMs=1.481965760578E12;TI;1,startTimeMs=1.481965758407E12;TI;1:NR
I/LoggerMetricsFactoryImpl( 1823): ScreenTime:updateLRUListLocked:page-type=KindleFramework;CK;1,hitType=deviceAction;CK;1,team-name=KindleFramework;CK;1,site_variant=KindleApplication;CK;1,page-action=fgEnd;CK;1,sub-page-type=tk.elevenk.proxysetter;CK;1,RequestId=94BF1EB14729A013983F;DV;1:NA
I/LoggerMetricsFactoryImpl( 1823): ScreenTime:updateLRUListLocked:page-type=KindleFramework;CK;1,hitType=deviceAction;CK;1,team-name=KindleFramework;CK;1,site_variant=KindleApplication;CK;1,page-action=fgStart;CK;1,sub-page-type=com.plexapp.android;CK;1,RequestId=57CFA8F14052BAAC8D6F;DV;1:NA
I/Vlog    ( 5823): performance:framesTotal:fgtracking=false;DV;1,key=tk.elevenk.proxysetter;DV;1,Counter=15.0;CT;1,unit=count;DV;1:HI
I/ActivityManager( 1823): addErrorToDropBox inserted hashcode=6f9fe98e210a4350ca950537e19c48699cb7ba4e for eventType crash.
I/Vlog    ( 1823): 1p_2p:bg_crash:fgtracking=false;DV;1,key=com.amazon.precog;DV;1,Counter=1.0;CT;1,unit=count;DV;1,metadata=6f9fe98e210a4350ca950537e19c48699cb7ba4e;DV;1:HI
I/AndroidRuntime(18839): Finished reporting FATAL to activityManagerService
I/CrashDescriptorUtil( 1823): addErrorToCommonLog Hash already present in file
I/libprocessgroup( 1823): Killing pid 18877 in uid 32059 as part of process group 18839
I/libprocessgroup( 1823): Killing pid 18877 in uid 32059 as part of process group 18839
I/Kernel  (  782): <3>[935067.386383] init: untracked pid 18877 killed by signal 9
I/ActivityManager( 1823): Process com.amazon.precog (pid 18839) has died
I/Vlog    ( 1823): activity_manager_service:sample_lifetime:fgtracking=false;DV;1,key=com.amazon.precog;DV;1,Counter=9.3503031E8;CT;1,unit=ms;DV;1,metadata=com.amazon.precog;DV;1:HI
I/Vlog    ( 1823): activity_manager_service:sample_died_oom_adj:fgtracking=false;DV;1,key=oom_adj_-12;DV;1,Counter=1.0;CT;1,unit=;DV;1,metadata=com.amazon.precog/com.amazon.precog;DV;1:HI
W/ActivityManager( 1823): Scheduling restart of crashed service com.amazon.precog/.storage.PersistenceManager$PersistService in 0ms
W/AmazonGidPackageManagerCallback( 1823): Launching com.amazon.precog (32059) with AMZ_APP_GID
W/art     (  774): PreZygoteFork called when we already have a zygote space.
I/ActivityManager( 1823): Start proc 9098:com.amazon.precog/u0a22059 for restart com.amazon.precog
D/VendorDisplayManagerGlobalCallback( 9098): callGetInstance: nil
E/WifiStateMachine( 1823): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=81.13 rxSuccessRate=86.07 targetRoamBSSID=any RSSI=-37
W/ActivityManager( 1823): getRunningAppProcesses: caller 32059 does not hold REAL_GET_TASKS; limiting output
D/ActivityManager( 1823): single user service: com.amazon.precog
D/ActivityManager( 1823): app = com.amazon.precog, has single user service, setting process record.
W/AmazonGidPackageManagerCallback( 1823): Launching com.amazon.device.settings (32026) with AMZ_APP_GID
W/art     (  774): PreZygoteFork called when we already have a zygote space.
I/ActivityManager( 1823): Start proc 9117:com.amazon.device.settings/u0a22026 for content provider com.amazon.device.settings/.SettingsProvider
I/art     (  774): Explicit concurrent mark sweep GC freed 8674(368KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 2MB/3MB, paused 213us total 17.883ms
I/art     (  774): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 39% free, 2MB/3MB, paused 213us total 14.404ms
I/art     (  774): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 39% free, 2MB/3MB, paused 213us total 14.495ms
D/VendorDisplayManagerGlobalCallback( 9117): callGetInstance: nil

**Comment by zcrself** [comment]
adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e host 192.168.1.9 -e port 8118 -e bypass plex.tv

**Comment by manadream** [comment]
Okay, so a few things, when you don't specify an SSID to connect to, it will use the first one available. 
Second, if the wifi network it finds and connects to needs a password, you would need to supply that in the command. 
Lastly, it looks like it thinks it is successfully connecting. The log lines 
`Proxy on dd-wrt with security SECURITY_NONE set to 192.168.1.9:8118 bypass: plex.tv` 
and 
` D/ProxySetterApp( 5823): Wifi connected and proxy set!` 
indicate it was successful. 
However, that may be an error as the log line 
` D/ProxySetterApp( 5823): Network ID dd-wrt with security SECURITY_PSK does not match requirements ssid = null and isSecured = false` 
indicates that the network is secured, but no password was provided.

My guess is that you need to specify the SSID and the password like so:
`adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e host 192.168.1.9 -e port 8118 -e bypass plex.tv -e ssid dd-wrt -e key InsertPasswordHere`

**Comment by zcrself** [comment]
thanks, I will try it again
