### ISSUE TITLE
How connect the specific network?

### ISSUE THREAD

**Issue by josinaldobarbosa** [jpkrause/AndroidProxySetter#16]
I use the 

> adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e host {myIp} -e port 8080 -e ssid {myNetwork} -e key {myPassword} -e reset-wifi true

settings are applied, but it is connected to another network with better signal or something else ...

**Comment by manadream** [comment]
hm, that's strange. May be a bug. Can you post the adb logcat logs from running the command? Also, you can try the command without `-e reset-wifi true`
