### ISSUE TITLE
Fire TV proxy issue

### ISSUE THREAD

**Issue by SPonnapula** [jpkrause/AndroidProxySetter#17]
Tried the below steps using Proxy Setter Tool:
1. Download the Apk (proxy-setter-release-0.1.3.apk) from https://github.com/jpkrause/AndroidProxySetter/releases
2. Side load the Apk file from laptop to Fire TV or Stick
3. Start the apk from laptop using below adb command
adb -s <Fire TV ip> shell am start -n tk.elevenk.proxysetter/.MainActivity -e host <Laptop ip> -e port 8888 -e ssid <Wifi Name> PrivateWifi -e key <Wifi password>

I am getting this error : Starting: Intent
{ cmp=tk.elevenk.proxysetter/.MainActivity (has extras) }

Can you please help?

**Comment by manadream** [comment]
Hi, can you give me more detailed logs by running `adb logcat` to get the logs from the Fire TV device? That message is a standard intent message and does not indicate what is actually happening.

**Comment by SPonnapula** [comment]
Thank you so much.  I think we are able to figure out the issue
