### ISSUE TITLE
Close Proxy

### ISSUE THREAD

**Issue by RengarAndKhz** [jpkrause/AndroidProxySetter#20]
Hi,

How can I shut down the proxy?

Best,

**Comment by manadream** [comment]
Hello,

Clearing the proxy is documented in the readme, but if you execute the following command it will clear it:
`adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e ssid <ssid> -e clear true`
Just replace <ssid> with the SSID of the wifi network your device is connected to that you want to clear the proxy from
