### ISSUE TITLE
Signing issues with APK

### ISSUE THREAD

**Issue by IzzySoft** [jpkrause/AndroidProxySetter#22]
On the APK from the latest release `apksigner` throws an error:

    ERROR: JAR signer CERT.RSA: JAR signature META-INF/CERT.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?

This means two things: newer versions of fdroidserver (I have to upgrade mine soon as the version I run isn't supported by the latest Android clients) will reject the package – and devices running Nougat or above certainly will as well.

Could you please check and fix this? Thanks!

**Comment by IzzySoft** [comment]
Update: As a couple of other projects had the same issues, I'd filed reports with them too. Two of them were able to solve it in a very easy way: Simply recompile the APK with a recent version of Android Studio.

* [CameraFilter](https://github.com/nekocode/CameraFilter/issues/15#issuecomment-341339598)
* [Bukanir](https://github.com/gen2brain/bukanir/issues/8#issuecomment-341268375)

Seems there was a bug in a previous version of it (probably when they started integrating v2-signing). So could you try that and let me know? Thanks in advance!

**Comment by IzzySoft** [comment]
Update again: Two more candidates solved it the very same way. Until now, there was none that tried this and failed, so our theory of a bug in a specific version of Android Studio seems to be confirmed. So unless you consider this project abandoned (please let us know in that case), may I ask you again to give this a try?

**Comment by manadream** [comment]
This isn't abandoned, just haven't had time to get to it yet.

**Comment by IzzySoft** [comment]
OK, so let's pray you find some :wink: Thanks for the feedback!

**Comment by manadream** [comment]
@IzzySoft try this one: https://github.com/jpkrause/AndroidProxySetter/releases/tag/v0.2.1
might be an answered prayer (crosses fingers) :stuck_out_tongue_closed_eyes:

**Comment by IzzySoft** [comment]
Looks good, Amen! :grin:

Thanks a lot!
