### ISSUE TITLE
Cannot remove/edit wifi configurations created manually or with another app on real device

### ISSUE THREAD

**Issue by crummy** [jpkrause/AndroidProxySetter#23]
When I try to set a proxy for my current wifi config that I set up manually, I get this log:
```
11-23 15:54:20.735  1189  1471 E WifiConfigManager: UID 10128 does not have permission to update configuration "Mindspace-Krausenstrasse"WPA_PSK
```
I see this behaviour a bunch with `reset-wifi true`. To be clear, here's my steps to repro:
1. Start with an Android 6+ device
2. By hand, open Settings and connect to a wifi network
3. Install AndroidProxySetter
4. Attempt to set the proxy
5. The above error will appear in logs

I believe this is because Android 6+ blocks the modification of WifiConfigurations to apps that are Device Owner or the app that created the WifiConfiguration in the first place. I actually came here looking for a solution to this problem, but it seems we're in the same boat. Wondered if anyone had any ideas on working around this: I want to be able to modify/remove WifiConfigurations that my app did not create.

**Comment by manadream** [comment]
I have not looked into this at all lately, but I have not seen a solution and would love to know one.

**Comment by crummy** [comment]
Here is the solution:

`adb shell settings put global http_proxy <address>:<port>`

It's lost at reboot, however.
