### ISSUE TITLE
Not able to set 5 digit port

### ISSUE THREAD

**Issue by igladun** [jpkrause/AndroidProxySetter#9]
Hello, 
I can't set a 5 digit port number. For example when I use this command
`adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e host 1.1.1.1 port 12345` port number will be set to 8080

Thanks

**Comment by manadream** [comment]
@igladun maybe it was a typo but you need another `-e` in that command: 
`adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e host 1.1.1.1 -e port 12345`
It's probably using 8080 because that is the default port it uses.

**Comment by igladun** [comment]
Thank you @jpkrause !
It works!
